ame: Python application

on:
  workflow_dispatch:
    inputs:
      post_body:
        type: string
        required: true

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      POST_BODY: ${{ github.event.inputs.post_body }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: run build
      run: |
        python3 cli.py
  
- uses: actions/upload-artifact@v3
  with:
    path: out.lanky